# -*- coding: utf-8 -*-
import os

MOD_NAME = "[MOD_NAME]"
MOD_DIR_NAME = "[MOD_DIR_NAME]"
CLIENT_SYSTEM_NAME = "[CLIENT_SYSTEM_NAME]"
SERVER_SYSTEM_NAME = "[SERVER_SYSTEM_NAME]"

CLIENT_SYSTEM_FILE_PATH = "ClientSystem.py"
SERVER_SYSTEM_FILE_PATH = "ServerSystem.py"

TEMPLATE_DIR_NAME = "template"
PLUGINS_DIR_NAME = "plugins"